server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: wechat-daily-report
    
  # Thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    encoding: UTF-8
      
  # Chatlog服务配置
  chatlog:
    default:
      base-url: http://127.0.0.1:5030
      timeout: 30000

# 日志配置
logging:
  level:
    com.wechat.dailyreport: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/wechat-report.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized